services:
  db:
    env_file: ./db/.env
    extra_hosts:
      - host.docker.internal:host-gateway
    healthcheck:
      interval: 2s
      retries: 2
      test: [ "CMD-SHELL", "psql -U $$POSTGRES_USERNAME -d $$POSTGRES_DB -c 'select 1' || exit 1" ]
    image: postgres:17-alpine
    ports:
      - 5432:5432
    shm_size: 128mb
    user: ${HOST_UID}:${HOST_GID}
    volumes:
      - ./db/data:/var/lib/postgresql/data

  dbmigrations:
    build: ./db
    depends_on:
      db:
        condition: service_healthy
    env_file: ./db/.env
    extra_hosts:
      - host.docker.internal:host-gateway
    user: ${HOST_UID}:${HOST_GID}
    volumes:
      - ./db/migrations:/migrations

  proxy:
    image: nginx:1.27
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 443:443
    volumes:
      - ./proxy-server/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy-server/fake-ca/domains/local.host:/ssl

  frontend:
    build: ./webapp
    env_file: ./webapp/.env
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 3000:3000

  ml:
    build: ./ml
    # TODO: env_file: ./ml/.env
    environment:
      - CC_RESOLUTION_MODEL_PATH=/ml/cc-resolution/cc-resolution.model/model.json
    ports:
      - 8101:8101
