services:
  proxy:
    depends_on:
      - frontend
      - ml
    image: nginx:1.27
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 443:443
    volumes:
      - ./proxy-server/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy-server/fake-ca/domains/local.host:/ssl

  frontend:
    build: ./frontend
    environment:
      - DATABASE_PATH=/data.db
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 3000:3000
    volumes:
      - ./data.db:/data.db

  ml:
    build: ./ml
    ports:
      - 8101:8101
