services:
  db:
    build: ./db
    env_file: ./db/.env
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 5432:5432
    shm_size: 128mb
    user: ${HOST_UID}:${HOST_GID}
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./db/migrations:/migrations
  proxy:
    image: nginx:1.27
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 443:443
    volumes:
      - ./proxy-server/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy-server/fake-ca/domains/local.host:/ssl

  frontend:
    build: ./webapp
    env_file: ./webapp/.env
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 3000:3000

  ml:
    build: ./ml
    # TODO: env_file: ./ml/.env
    environment:
      - CC_RESOLUTION_MODEL_PATH=/ml/cc-resolution/cc-resolution.model/model.json
    ports:
      - 8101:8101
