CREATE USER $SERVICE_USER WITH PASSWORD '$SERVICE_PASSWORD';
GRANT ALL ON DATABASE $POSTGRES_DB TO $SERVICE_USER;
CREATE TABLE public.migrations(
	id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	created_at TIMESTAMP DEFAULT now(),
	name TEXT UNIQUE NOT NULL
);
GRANT ALL ON TABLE public.migrations TO $SERVICE_USER;
