#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $SERVICE_USER WITH PASSWORD '$SERVICE_PASSWORD';
	GRANT ALL ON DATABASE $POSTGRES_DB TO $SERVICE_USER;
EOSQL
